// <auto-generated />
namespace commissioning_assistance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Added_CommissionFinished_Boolean : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_CommissionFinished_Boolean));
        
        string IMigrationMetadata.Id
        {
            get { return "202001121519145_Added_CommissionFinished_Boolean"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
